INSERT INTO tb_category (name, created_at) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Smartphones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Tablets', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Laptops', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Monitors', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Keyboards', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Mice', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Headphones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Cameras', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Televisions', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Video Games', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Gaming Consoles', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Accessories', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Kitchen', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Fitness', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Tools', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('School Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Software', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Networking', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Smart Home', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Outdoor', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Travel', NOW());